Repository fylein/fyle-qbd-api, pull requests merged in 2025-03, with the labels that each got.

#127 feat: POST to integrations settings API on onboarding completion
  apps/fyle/helpers.py
  apps/workspaces/serializers.py
  apps/workspaces/tasks.py
  quickbooks_desktop_api/settings.py
  quickbooks_desktop_api/tests/settings.py
  scripts/python/003_create_integration_records.py
Labels: size/M

#130 fix: Django Vul
  requirements.txt
Labels: size/XS

#131 Feat: Add health check
  Dockerfile
  health_check.sh
Labels: size/S

#133 chore: Bump Rest Auth
  quickbooks_desktop_api/settings.py
  requirements.txt
Labels: size/XS

#134 feat: Add support for Update fyle creds
  apps/workspaces/tasks.py
  tests/test_workspaces/test_tasks.py
Labels: size/S

#132 fix: Run container with non root user
  Dockerfile
  docker-compose-pipeline.yml
Labels: size/XS
