Repository fylein/fyle-qbd-api, pull requests merged in 2025-06, with the labels that each got.

#143 chore: remove security scan workflow
  .github/workflows/security-scan.yml
Labels: size/S

#144 chore: bump django version
  .github/workflows/codecov.yml
  .github/workflows/tests.yml
  requirements.txt
Labels: size/XS

#146 fix: remove unwanted steps from workflow
  .github/workflows/codecov.yml
  .github/workflows/tests.yml
  codecov.yml
Labels: size/M
