Repository fylein/fyle-qbd-api, pull requests merged in 2025-01, with the labels that each got.

#117 fix: redact S3 URLs in fixtures
  tests/test_fyle/fixtures.py
Labels: size/XS

#118 chore: remove unused package
  requirements.txt
Labels: size/XS

#120 fix: lib dependencies
  apps/qbd/apps.py
  quickbooks_desktop_api/sentry.py
  quickbooks_desktop_api/settings.py
  quickbooks_desktop_api/tests/settings.py
  requirements.txt
Labels: size/S

#119 feat: changes related to QBD connector migration
  apps/fyle/helpers.py
  apps/workspaces/migrations/0029_workspace_migrated_to_qbd_direct.py
  apps/workspaces/models.py
  apps/workspaces/serializers.py
  apps/workspaces/tasks.py
  apps/workspaces/urls.py
  apps/workspaces/views.py
  docker-compose-pipeline.yml
  quickbooks_desktop_api/settings.py
  quickbooks_desktop_api/tests/settings.py
  tests/test_workspaces/test_tasks.py
  tests/test_workspaces/test_views.py
Labels: deploy, size/L

#121 fix: change logging and error raising
  apps/fyle/helpers.py
  apps/workspaces/tasks.py
  tests/test_workspaces/test_tasks.py
Labels: size/M

#122 fix: ignore webhook fyle callback
  apps/fyle/queue.py
Labels: size/XS

#123 feat: POST to integrations settings API on onboarding completion
  apps/fyle/helpers.py
  apps/workspaces/serializers.py
  apps/workspaces/tasks.py
  quickbooks_desktop_api/settings.py
  quickbooks_desktop_api/tests/settings.py
Labels: size/S

#125 fix: get access token
  apps/fyle/helpers.py
  apps/workspaces/tasks.py
  tests/test_fyle/test_helpers.py
Labels: size/XS

#126 fix: Revert "feat: POST to integrations settings API on onboarding completion (#123)"
  apps/fyle/helpers.py
  apps/workspaces/serializers.py
  apps/workspaces/tasks.py
  quickbooks_desktop_api/settings.py
  quickbooks_desktop_api/tests/settings.py
Labels: size/S
